# Site settings
title: ZhuYuanhao's Blog
email: yhzhu061@163.com
description: > # this means to ignore newlines until "baseurl:"
  温故而知新 <br/>
  积跬步而成千里 <br/>
  不忘初心，方得始终
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zhuyuanhao.com" # the base hostname & protocol for your site
github_username:  zhuyuanhao

# Build settings
markdown: kramdown
kramdown: 
  toc_levels: "1,2"
highlighter:	  pygments
paginate:         7

safe: true
lsi: false

comments :
    provider : duoshuo
    duoshuo :
          short_name : suhacker
